### ISSUE TITLE
SSL issues for edge:drivers:logcat

### ISSUE THREAD

**Issue by rafaelborja** [SmartThingsCommunity/edge-cli-plugin#26]
Issue described in a community post https://community.smartthings.com/t/how-to-enable-logging-on-the-hub/230465/53

The following error message is shown when trying to connect logcat 
![image](https://user-images.githubusercontent.com/5069188/141718769-6de624ce-8f9b-48e8-9680-ba3346426465.png)

Issue is caused by a hardcoded "https"  at https://github.com/SmartThingsCommunity/edge-cli-plugin/blob/c3bfd601807407d8911e71e9c6de47cd5c95a41b/src/lib/live-logging.ts#L184 since this version of firmhware does not support https for logging.

Changing https to http and commenting line https://github.com/SmartThingsCommunity/edge-cli-plugin/blob/c3bfd601807407d8911e71e9c6de47cd5c95a41b/src/lib/live-logging.ts#L214 allows cli to connect to hub using catlog (see bellow)

![image](https://user-images.githubusercontent.com/5069188/141718526-600246ab-a920-4ea2-b9c9-94e330acdde6.png)

Hub version:

![image](https://user-images.githubusercontent.com/5069188/141718755-2a8efb55-71c9-47cb-b359-5df4c212d7ce.png)

**Comment by posborne** [comment]
Hi @rafaelborja thanks for the report!  The underlying problem here is that the firmware for ST WiFi doesn't yet have support for the beta edge drivers feature due to some extra work that was not yet implemented to provide an implementation of the drivers sandbox for that target.  In any hub implementation that supports drivers, TLS with certification verification will be provided so I don't believe a patch to drop TLS will be appropriate.  This patch allows for a connection to take place but will not ever provide any logs in place.

@rossiam This issue can be closed.  The thread you link on the forums should receive news when we have an update about availability of edge drivers beta on the ST WiFi platform.
